Fix compilation error in documented example
A missing opening `{` causes the following compilation error:

```
Unmatched right curly bracket at t/001-basics.t line 6, at end of line
syntax error at t/001-basics.t line 6, near "'t/schema/postgresql.sql'}"
t/001-basics.t had compilation errors.
```

This small change corrects the documentation by adding the missing opening `{`.